<ol>
    <?php foreach ($this->getItems() as $_item): ?>
        <li>
            <?php if ($_item->getCount() > 0): ?>
                <input type="checkbox"<?php if ($_item->isSelected()): ?> checked="checked" <?php endif; ?>
                <?php if ($this->helper('catalin_seo')->isAjaxEnabled()): ?>
                           onclick="$(this).next().click()"
                       <?php else: ?>
                           onclick="setLocation('<?php echo ($_item->isSelected()) ? $this->urlEscape($_item->getRemoveUrl()) : $this->urlEscape($_item->getUrl()) ?>')"
                       <?php endif; ?>
                       />
                <a 
                <?php if ($_item->isSelected()): ?>
                        onclick="$(this).previous().checked = false;" 
                    <?php else: ?>
                        onclick="$(this).previous().checked = true;" 
                    <?php endif; ?>                            
                    href="<?php echo ($_item->isSelected()) ? $_item->getRemoveUrl() : $_item->getUrl() ?>"
                    ><?php echo $_item->getLabel() ?></a>
                <?php else: ?>
                    <?php echo $_item->getLabel() ?>
                <?php endif; ?>
            (<?php echo $_item->getCount() ?>)
        </li>
    <?php endforeach ?>
</ol>