<div class="main-col-inner">
    <div class="<?php echo $this->getContainerCssClass() ?>">
        <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

        <?php echo $this->getChildHtml('content') ?>
        <script type="text/javascript">
            <?php if (Mage::getStoreConfig('cms/wysiwyg/enabled') == Mage_Cms_Model_Wysiwyg_Config::WYSIWYG_ENABLED): ?>
                $('togglepage_content').click();
            <?php endif; ?>
            $('page_tabs_main_section').show();
        </script>
    </div>
    <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
</div>
<?php echo $this->getChildHtml('js') ?>
