<?php
/**
 * Fontis Blog Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * Parts of this software are derived from code originally developed by
 * Robert Chambers <magento@robertchambers.co.uk>
 * and released as "Lazzymonk's Blog" 0.5.8 in 2009.
 *
 * @category   Fontis
 * @package    Fontis_Blog
 * @copyright  Copyright (c) 2013 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$blogHelper = Mage::helper("blog");
$threadedComments = $this->getComments();
$gravEnabled = $this->isGravatarEnabled();
$gravSize = $this->getGravatarSize();
?>
<?php foreach ($threadedComments as $key => $value): ?>
    <?php $comment = $value["currentComment"]; ?>
    <div class="commentWrapper">
        <div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
        <div class="commentDetails" style="height: <?php echo $gravEnabled ? 15 + $gravSize : 15; ?>px;">
            <?php if (!($blogHelper->isLoginRequired() && !($this->helper('customer')->isLoggedIn()))): ?>
                <div class="commentReply"><a href="#postComment" onClick="setupReply(<?php echo $key; ?>);"><?php echo $blogHelper->__("Reply"); ?></a></div>
            <?php endif; ?>
            <div class="commentPostDetails">
                <?php if ($this->isGravatarEnabled()): ?>
                <div class="commentGravatar">
                <img src="<?php echo $this->getGravatarUrl($comment->getEmail()); ?>" alt="" width="<?php echo $gravSize; ?>" height="<?php echo $gravSize; ?>" />
                </div>
                <?php endif; ?>
                <div class="commentUserDetails">
                <?php echo $blogHelper->__('Comment by'); ?> <span id="commentUser_<?php echo $key; ?>"><?php echo $comment->getUser(); ?></span> - <?php echo $comment->getCreatedTime(); ?>
                </div>
            </div>
        </div>
        <?php if (!empty($value["children"])): ?>
            <div class="commentIndent">
                <?php echo $this->getLayout()->createBlock("blog/post")->setTemplate("fontis/blog/post/comments.phtml")->setComments($value["children"])->toHtml(); ?>
            </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
