<?php
/**
 * Unirgy_Giftcert extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Unirgy
 * @package    Unirgy_Giftcert
 * @copyright  Copyright (c) 2008 Unirgy LLC
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * @category   Unirgy
 * @package    Unirgy_Giftcert
 * @author     Boris (Moshe) Gurevich <moshe@unirgy.com>
 */
?>
<?php
if (Mage::getSingleton('ugiftcert/cert')->getOrderTotalDrawn()) {
    return;
}
Mage::getSingleton('ugiftcert/cert')->setOrderTotalDrawn(1);

$_order = $this->getParentBlock()->getOrder();
?>
<?php if ($_order->getGiftcertCode()): ?>
<tr>
<?php if ($this->getColspan()): ?>

    <td colspan="<?php echo $this->getColspan() ?>" class="a-right"><?php echo $this->__('Gift certificate(s): %s', $_order->getGiftcertCode()) ?></td>
    <td class="last a-right"><?php echo $_order->formatPrice($_order->getGiftcertAmount()) ?></td>

<?php else: ?>

    <tr>
        <td colspan="3" align="right" style="padding:3px 9px"><?php echo $this->__('Gift certificate(s): %s', $_order->getGiftcertCode()) ?></td>
        <td align="right" style="padding:3px 9px"><?php echo $_order->formatPrice($_order->getGiftcertAmount()) ?></td>
    </tr>

<?php endif; ?>
</tr>
<?php endif; ?>