<?php
/**
 * Fontis Blog Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * Parts of this software are derived from code originally developed by
 * Robert Chambers <magento@robertchambers.co.uk>
 * and released as "Lazzymonk's Blog" 0.5.8 in 2009.
 *
 * @category   Fontis
 * @package    Fontis_Blog
 * @copyright  Copyright (c) 2013 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
$post = $this->getPost();
$postAddress = $post->getAddress();
$postTitle = $post->getTitle();
$baseImageUrl = Mage::helper("blog")->getBookmarkImagesRoute();
?>
<div class="postBookmarks"><h4>Bookmark with:</h4>
	<a href="http://digg.com/submit?phase=2&amp;url=<?php echo $postAddress; ?>&amp;title=<?php echo $postTitle; ?>&amp;bodytext=<?php echo $postTitle; ?>&amp;topic=" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/digg.gif" width="16" border="0" height="16" alt="" />&nbsp;Digg</a>&nbsp;
	<a href="http://www.stumbleupon.com/submit?url=<?php echo $postAddress; ?>&amp;title=<?php echo $postTitle; ?>&amp;newcomment=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/stumbleupon.gif" width="16" border="0" height="16" alt="" />&nbsp;Stumbleupon</a>&nbsp;
	<a href="http://delicious.com/post/?url=<?php echo $postAddress; ?>&amp;title=<?php echo $postTitle; ?>&amp;notes=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/delicious.gif" width="16" border="0" height="16" alt="" />&nbsp;Delicious</a>&nbsp;
	<a href="http://www.facebook.com/sharer.php?u=<?php echo $postAddress; ?>&amp;t=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/facebook.gif" width="16" border="0" height="16" alt="" />&nbsp;Facebook</a>&nbsp;
	<a href="http://reddit.com/submit?url=<?php echo $postAddress; ?>&amp;title=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/reddit.gif" width="16" border="0" height="16" alt="" />&nbsp;Reddit</a>&nbsp;
</div>
<?php
/*
Below is a list of other bookmarking sites that you can use.
simply copy and past the lines you want to above.

<a href="http://www.google.com/bookmarks/mark?op=add&amp;bkmk=<?php echo $postAddress;?>&amp;title=<?php echo $postTitle; ?>&amp;annotation=<?php echo $postTitle; ?>&amp;cd=bm&amp;btnA=Add" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/google.gif" width="16" border="0" height="16" alt="" />&nbsp;Google</a>&nbsp;
<a href="http://digg.com/submit?phase=2&amp;url=<?php echo $postAddress;?>&amp;title=<?php echo $postTitle; ?>&amp;bodytext=<?php echo $postTitle; ?>&amp;topic=" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/digg.gif" width="16" border="0" height="16" alt="" />&nbsp;Digg</a>&nbsp;
<a href="http://www.stumbleupon.com/submit?url=<?php echo $postAddress;?>&amp;title=<?php echo $postTitle; ?>&amp;newcomment=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/stumbleupon.gif" width="16" border="0" height="16" alt="" />&nbsp;Stumbleupon</a>&nbsp;
<a href="http://technorati.com/faves/?add=<?php echo $postAddress;?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/technorati.gif" width="16" border="0" height="16" alt="" />&nbsp;Technorati</a>&nbsp;
<a href="http://www.myspace.com/Modules/PostTo/Pages/?c=<?php echo $postAddress;?>&amp;t=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/myspace.gif" width="16" border="0" height="16" alt="" />&nbsp;MySpace</a>&nbsp;
<a href="http://www.facebook.com/sharer.php?u=<?php echo $postAddress;?>&amp;t=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/facebook.gif" width="16" border="0" height="16" alt="" />&nbsp;Facebook</a>&nbsp;
<a href="http://delicious.com/post/?url=<?php echo $postAddress; ?>&amp;title=<?php echo $postTitle; ?>&amp;notes=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/delicious.gif" width="16" border="0" height="16" alt="" />&nbsp;Delicious</a>&nbsp;
<a href="http://twitter.com/home?status=<?php echo $postTitle; ?>%20<?php echo $postAddress; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/twitter.gif" width="16" border="0" height="16" alt="" />&nbsp;Twitter</a>&nbsp;
<a href="http://cgi.fark.com/cgi/fark/submit.pl" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/fark.gif" width="16" border="0" height="16" alt="" />&nbsp;Fark</a>&nbsp;
<a href="https://favorites.live.com/quickadd.aspx?marklet=1&amp;mkt=en-us&amp;url=<?php echo $postAddress; ?>&amp;title=<?php echo $postTitle; ?>&amp;top=1" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/live-favourites.gif" width="16" border="0" height="16" alt="" />&nbsp;Live</a>&nbsp;
<a href="http://bookmarks.yahoo.com/toolbar/savebm?opener=tb&amp;u=<?php echo $postAddress; ?>&amp;t=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/yahoo.gif" width="16" border="0" height="16" alt="" />&nbsp;Yahoo Bookmarks</a>&nbsp;
<a href="http://myjeeves.ask.com/mysearch/BookmarkIt?v=1.2&amp;t=webpages&amp;url=<?php echo $postAddress; ?>&amp;title=<?php echo $postTitle; ?>&amp;abstext=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/myjeeves.gif" width="16" border="0" height="16" alt="" />&nbsp;MyJeeves</a>&nbsp;
<a href="http://reddit.com/submit?url=<?php echo $postAddress; ?>&amp;title=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/reddit.gif" width="16" border="0" height="16" alt="" />&nbsp;Reddit</a>&nbsp;
<a href="http://slashdot.org/slashdot-it.pl?op=basic&amp;url=<?php echo $postAddress; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/slashdot.gif" width="16" border="0" height="16" alt="" />&nbsp;Slashdot</a>&nbsp;
<a href="http://faves.com/Authoring.aspx?u=<?php echo $postAddress; ?>&amp;t=<?php echo $postTitle; ?>&amp;noteText=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/faves.gif" width="16" border="0" height="16">&nbsp;Faves.com</a>&nbsp;
<a href="http://www.furl.net/savedialog.jsp?p=1&amp;t=<?php echo $postTitle; ?>&amp;u=<?php echo $postAddress; ?>&amp;r=&amp;v=1&amp;c=<?php echo $postTitle; ?>&amp;topics=<?php echo $postTitle; ?>&amp;description=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/furl.gif" width="16" border="0" height="16" alt="" />&nbsp;Furl.net</a>&nbsp;
<a href="http://blogmarks.net/my/marks,new?url=<?php echo $postAddress; ?>&amp;title=<?php echo $postTitle; ?>&amp;content=<?php echo $postTitle; ?>&amp;via=<?php echo $postAddress; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/blogmarks.gif" width="16" border="0" height="16" alt="" />&nbsp;Blogmarks.net</a>&nbsp;
<a href="http://www.netvouz.com/action/submitBookmark?url=<?php echo $postAddress; ?>&amp;name=<?php echo $postTitle; ?>&amp;description=<?php echo $postTitle; ?>&amp;note=<?php echo $postTitle; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/netvouz.gif" width="16" border="0" height="16" alt="" />&nbsp;Netvouz</a>&nbsp;
<a href="http://ideas.mailtrust.com/submit.php?url=<?php echo $postAddress; ?>" class="bm" target="_blank"><img src="<?php echo $baseImageUrl; ?>/mailtrust.gif" width="16" border="0" height="16">&nbsp;Ideas.mailtrust.com</a>&nbsp;
*/
