<?php
/**
 * Fontis Blog Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * Parts of this software are derived from code originally developed by
 * Robert Chambers <magento@robertchambers.co.uk>
 * and released as "Lazzymonk's Blog" 0.5.8 in 2009.
 *
 * @category   Fontis
 * @package    Fontis_Blog
 * @copyright  Copyright (c) 2013 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php

$collection = $this->getCollection();
$currentPage = (int) $this->getRequest()->getParam('page');
if (!$currentPage) {
    $currentPage = 1;
}
$pages = ceil(count($collection) / 2);
$links = "";

if ($currentPage != 1) {
    echo '<a href="' . $this->getUrl("blog/page") . ($currentPage - 1) . '" >' . Mage::helper("blog")->__("Newer Posts") . '</a>';
}
if ($currentPage != $pages) {
    echo '<a href="' . $this->getUrl("blog/page") . ($currentPage + 1) . '" >' . Mage::helper("blog")->__("Older Posts") . '</a>';
}
