<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('customerattribute')->__('Manage attributes') ?></h3></td>
        <td class="a-right">
        </td>
    </tr>
</table>
</div>
<div>
    <div align="center">
    	<h3 class="icon-head"><u><?php echo Mage::helper('customerattribute')->__('Choose attributes to manage') ?></u></h3>
    	<br/><br/>
    	<h3 class="icon-head">
    	<a href="<?php echo $this->getUrl('*');?>index/category/filter//"><?php echo Mage::helper('customerattribute')->__('Categories attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/customer/filter//"><?php echo Mage::helper('customerattribute')->__('Customers attributes') ?></a>
    	<br/>
    	<a href="<?php echo $this->getUrl('*');?>index/address/filter//"><?php echo Mage::helper('customerattribute')->__('Customer\'s address attributes') ?></a></h3>
    </div>
</div>